### ISSUE TITLE
no such file or directory, open '/app/package.json'

### ISSUE THREAD

**Issue by christofkac** [aidancrowther/Odysseus#5]
Hi,
I wanted to give this tool a try in the docker environment as it sounds interesting.
Unfortunately, it did not work for me.
What I did:
```
git clone https://github.com/aidancrowther/Odysseus
docker build -t odysseus:latest .
docker run -d -p 8080:80 odysseus
```

Result when running the container:
```
today at 12:36:47 npm ERR! path /app/package.json
today at 12:36:47 npm ERR! code ENOENT
today at 12:36:47 npm ERR! errno -2
today at 12:36:47 npm ERR! syscall open
today at 12:36:47 npm ERR! enoent ENOENT: no such file or directory, open '/app/package.json'
today at 12:36:47 npm ERR! enoent This is related to npm not being able to find a file.
today at 12:36:47 npm ERR! enoent 
today at 12:36:47
today at 12:36:47 npm ERR! A complete log of this run can be found in:
today at 12:36:47 npm ERR!     /root/.npm/_logs/2021-10-17T10_36_47_393Z-debug.log
today at 12:44:12 Container stopped

```

And idea what I did wrong?
Thanks
Christof

**Comment by aidancrowther** [comment]
Hi Christof,

I'm sorry for my delay in replying. It seems that the .gitignore was misconfigured causing the package.json file to be dropped from the repo. I have reconfigured it and pushed upstream to fix the issue. Hopefully, this works for you!

Thanks,
Aidan Crowther
